/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsystem;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HAMZA
 */
public class search_std extends javax.swing.JFrame {
   

    private void close()
{
    WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
        } 
    
    Connection con;
Statement st;
ResultSet rs;
PreparedStatement ps;
public void connect()
{try{
  String host="jdbc:sqlserver://localhost:1433;databaseName=smsystem";
  String user="sa";
  String pwd="123";
    con=DriverManager.getConnection(host, user, pwd);
    st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
       
        
}
catch(Exception e)
{
    System.out.println("error");
}
}

    /**
     * Creates new form search_std
     */
    public search_std() {
        initComponents();
        connect();
        fillcombo();
       // tables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        mont = new javax.swing.JTextField();
        fee = new javax.swing.JTextField();
        en = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        classs = new javax.swing.JTextField();
        smonth = new javax.swing.JLabel();
        sfee = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        serc_id = new javax.swing.JLabel();
        sage = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        sen = new javax.swing.JLabel();
        sclass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Student");

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(0, 0, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(51, 51, 51));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 153, 153));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        combo.setForeground(new java.awt.Color(51, 51, 51));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo, javax.swing.GroupLayout.Alignment.LEADING, 0, 75, Short.MAX_VALUE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(search)
                .addGap(18, 18, 18)
                .addComponent(back)
                .addGap(26, 26, 26)
                .addComponent(clear)
                .addGap(18, 18, 18)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        smonth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        smonth.setForeground(new java.awt.Color(51, 51, 51));
        smonth.setText("Month");

        sfee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sfee.setForeground(new java.awt.Color(51, 51, 51));
        sfee.setText("Fee");

        serc_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        serc_id.setForeground(new java.awt.Color(51, 51, 51));
        serc_id.setText("Id");

        sage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sage.setForeground(new java.awt.Color(51, 51, 51));
        sage.setText("Age");

        sname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sname.setForeground(new java.awt.Color(51, 51, 51));
        sname.setText("Name");

        sen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sen.setForeground(new java.awt.Color(51, 51, 51));
        sen.setText("Enroll.No.");

        sclass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sclass.setForeground(new java.awt.Color(51, 51, 51));
        sclass.setText("Class");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sname)
                    .addComponent(sclass)
                    .addComponent(sen)
                    .addComponent(sage)
                    .addComponent(smonth)
                    .addComponent(sfee)
                    .addComponent(serc_id))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mont, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(age, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(en, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classs, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serc_id)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sname)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sclass)
                    .addComponent(classs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sen)
                    .addComponent(en, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sage)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smonth)
                    .addComponent(mont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sfee)
                    .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
close();
        main o=new main();
    o.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
try{
        String idd=id.getText();
int i=Integer.parseInt(idd);
 String sql="select name,class,enroll,age,month,fee from student inner join fees on student.id=fees.sid where student.id='"+i+"'";
 ps=con.prepareStatement(sql);
 rs=ps.executeQuery();
 while(rs.next())
 {
     
     String names=rs.getString("name");
        String clas=rs.getString("class");
        String enr=rs.getNString("enroll");
        String ages=rs.getString("age");
        String montt=rs.getNString("month");
        String fees=rs.getNString("fee");
       name.setText(names);
       classs.setText(clas);
       en.setText(enr);
       age.setText(ages);
       mont.setText(montt);
       fee.setText(fees);
 }
 
 
}
catch(Exception e)
{  JOptionPane.showMessageDialog(null, "Data Not Found or Fee Not Paid  Yet");
    System.out.println("search error");
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
id.setText("");
name.setText("");
classs.setText("");
en.setText("");
age.setText("");
mont.setText("");
fee.setText("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_std.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_std.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_std.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_std.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_std().setVisible(true);
            }
        });
    }

    
    private void fillcombo()
    {
        try{
           String sql="select name from student";
           ps=con.prepareStatement(sql);
           rs=ps.executeQuery();
           while(rs.next())
           {
               String names=rs.getString("name");
               combo.addItem(names);
               
               
           }
            
        }
        catch(Exception e )
        {
            System.out.println("combo error");
        }
        
    }
//    private void tables()
//    {
//        try{
//            String sql="select name,class,enroll,age,month,fee from student inner join fees on student.id=fees.sid";
//            ps=con.prepareStatement(sql);
//            rs=ps.executeQuery();
//            table.setModel(DbUtils.ResultSet(rs)) ;
//            
//        }
//        catch(Exception e)
//        {
//            System.out.println("table error"); 
//        }
//    }
//           
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton back;
    private javax.swing.JTextField classs;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox combo;
    private javax.swing.JTextField en;
    private javax.swing.JTextField fee;
    private javax.swing.JTextField id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField mont;
    private javax.swing.JTextField name;
    private javax.swing.JLabel sage;
    private javax.swing.JLabel sclass;
    private javax.swing.JButton search;
    private javax.swing.JLabel sen;
    private javax.swing.JLabel serc_id;
    private javax.swing.JLabel sfee;
    private javax.swing.JLabel smonth;
    private javax.swing.JLabel sname;
    // End of variables declaration//GEN-END:variables
}
